// CropsIntel V3 — Convenience type aliases
//
// `database.types.ts` is auto-generated by `supabase gen types typescript`.
// That file gets overwritten on every regeneration, so we keep app-level type
// aliases here. Whenever a new table or enum is added to the schema, add the
// corresponding alias below.

import type { Database } from "./database.types"

// Enums
export type AppRole = Database["public"]["Enums"]["app_role"]
export type CompanyType = Database["public"]["Enums"]["company_type"]
export type VerificationStatus = Database["public"]["Enums"]["verification_status"]
export type ProductType = Database["public"]["Enums"]["product_type"]
export type UserTier = Database["public"]["Enums"]["user_tier"]
export type RelationshipRole = Database["public"]["Enums"]["relationship_role"]
export type IntelSource = Database["public"]["Enums"]["intel_source"]

// Table row types (use these in components / hooks)
export type Commodity = Database["public"]["Tables"]["commodities"]["Row"]
export type Company = Database["public"]["Tables"]["companies"]["Row"]
export type Contact = Database["public"]["Tables"]["contacts"]["Row"]
export type CanonicalProduct = Database["public"]["Tables"]["canonical_products"]["Row"]
export type Profile = Database["public"]["Tables"]["profiles"]["Row"]
export type Relationship = Database["public"]["Tables"]["relationships"]["Row"]
export type MarketIntelligence = Database["public"]["Tables"]["market_intelligence"]["Row"]
export type ZyraConversation = Database["public"]["Tables"]["zyra_conversations"]["Row"]
export type UserRole = Database["public"]["Tables"]["user_roles"]["Row"]
export type AgentAuditLog = Database["public"]["Tables"]["agent_audit_log"]["Row"]
export type AgentRateLimit = Database["public"]["Tables"]["agent_rate_limits"]["Row"]
export type ScopeViolation = Database["public"]["Tables"]["scope_violations"]["Row"]

// Insert / Update variants — use when writing to the DB
export type CommodityInsert = Database["public"]["Tables"]["commodities"]["Insert"]
export type CompanyInsert = Database["public"]["Tables"]["companies"]["Insert"]
export type ContactInsert = Database["public"]["Tables"]["contacts"]["Insert"]
export type ProfileUpdate = Database["public"]["Tables"]["profiles"]["Update"]
