import { council } from '../council'
import {
  getDoneTaskIds,
  getQueuedTaskIds,
  parsePhases,
  readMasterPlan,
  writeTaskSpec,
} from '../lib/plan-reader'
import { buildTaskSpecPrompt, buildArchitecturalCheckPrompt } from '../prompts/task-spec-prompt'
import { askOpenAI } from '../providers/openai'
import { CouncilInput } from '../types'
import simpleGit from 'simple-git'
import * as path from 'path'

const MAX_TASKS_PER_RUN = 1

export async function runAutoTaskWriter(): Promise<void> {
  console.log('[Council:auto-task-writer] Starting...')

  let masterPlan: string
  try {
    masterPlan = readMasterPlan()
  } catch (err) {
    console.error('[Council:auto-task-writer] Cannot read master plan:', err instanceof Error ? err.message : err)
    process.exit(1)
  }

  const phases = parsePhases(masterPlan)
  console.log(`[Council:auto-task-writer] Found ${phases.length} phases in master plan`)

  if (phases.length === 0) {
    console.log('[Council:auto-task-writer] No phases found — nothing to do')
    return
  }

  const done = getDoneTaskIds()
  const queued = getQueuedTaskIds()

  const pending = phases.filter(p => !done.has(p.id) && !queued.has(p.id))
  console.log(`[Council:auto-task-writer] ${pending.length} phases not yet queued or done`)

  if (pending.length === 0) {
    console.log('[Council:auto-task-writer] All phases are either done or queued — nothing to generate')
    return
  }

  let generated = 0
  for (const phase of pending.slice(0, MAX_TASKS_PER_RUN)) {
    console.log(`[Council:auto-task-writer] Generating task spec for ${phase.id}: ${phase.name}`)

    // Extract relevant section from master plan
    const excerpt = masterPlan.slice(0, 4000) // Use first 4k chars as context

    const question = buildTaskSpecPrompt(phase, excerpt)

    const input: CouncilInput = {
      question,
      context: { phaseId: phase.id, phaseName: phase.name },
      mode: 'auto-task-writer',
      depth: 'quick',
      invokedBy: 'council:auto-task-writer',
    }

    try {
      const output = await council(input)
      let taskSpec = output.finalDecision

      // Check if spec has architectural decisions that need Deep Council
      const archCheckPrompt = buildArchitecturalCheckPrompt(taskSpec)
      const archCheck = await askOpenAI(archCheckPrompt)

      try {
        const archJson = archCheck.content
        const start = archJson.indexOf('{')
        const end = archJson.lastIndexOf('}')
        if (start !== -1 && end !== -1) {
          const parsed = JSON.parse(archJson.slice(start, end + 1)) as { hasArchitecturalDecision?: boolean }
          if (parsed.hasArchitecturalDecision) {
            taskSpec += '\n\n<!-- council:needs-deep-review -->\n'
            console.log(`[Council:auto-task-writer] Task ${phase.id} flagged for Deep Council review`)
          }
        }
      } catch (_e) {/* ignore parse errors */}

      const filePath = writeTaskSpec(phase.id, taskSpec)
      console.log(`[Council:auto-task-writer] Task spec written: ${filePath}`)
      generated++

      // Commit and push
      await commitAndPush(phase.id, filePath)
    } catch (err) {
      console.error(`[Council:auto-task-writer] Failed to generate task for ${phase.id}:`, err instanceof Error ? err.message : err)
    }
  }

  console.log(`[Council:auto-task-writer] Done. Generated ${generated} task spec(s).`)
}

async function commitAndPush(phaseId: string, filePath: string): Promise<void> {
  const repoRoot = path.join(process.cwd(), '..')

  try {
    const git = simpleGit(repoRoot)

    // Setup SSH key if available
    const sshKey = process.env.AGENT_SSH_PRIVATE_KEY
    if (sshKey) {
      const fs = await import('fs')
      const os = await import('os')
      const keyPath = path.join(os.tmpdir(), 'council_ssh_key')
      fs.writeFileSync(keyPath, sshKey, { mode: 0o600 })
      await git.env({ GIT_SSH_COMMAND: `ssh -i ${keyPath} -o StrictHostKeyChecking=no` })
    }

    await git.add(filePath)
    await git.commit(`chore(council): auto-generate task spec for ${phaseId}\n\n🤖 Generated by CropsIntel V3 Council (auto-task-writer)`)
    await git.push('origin', 'main')
    console.log(`[Council:auto-task-writer] Committed and pushed task spec for ${phaseId}`)
  } catch (err) {
    console.error(`[Council:auto-task-writer] Git push failed (spec still written):`, err instanceof Error ? err.message : err)
  }
}
