-- Council: Multi-Brain Architect tables
-- Audit log for every council invocation (both quick and deep modes)
CREATE TABLE IF NOT EXISTS public.council_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  mode text NOT NULL CHECK (mode IN ('cli','auto-task-writer','runtime')),
  depth text NOT NULL CHECK (depth IN ('quick','deep')),
  question text NOT NULL,
  context jsonb DEFAULT '{}'::jsonb,
  -- Quick mode columns (null for deep)
  quick_claude jsonb,
  quick_gpt jsonb,
  quick_gemini jsonb,
  quick_judge jsonb,
  -- Deep mode columns (null for quick)
  pair_session_1 jsonb,
  pair_session_2 jsonb,
  pair_session_3 jsonb,
  tri_council jsonb,
  validation_claude jsonb,
  validation_gpt jsonb,
  validation_gemini jsonb,
  -- Common
  final_decision text NOT NULL,
  confidence numeric,
  cost_usd numeric NOT NULL DEFAULT 0,
  duration_ms int,
  invoked_by text,
  invoked_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.council_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team can read council runs" ON public.council_runs
  FOR SELECT USING (public.has_role(auth.uid(), 'team'));

-- Architecture Decision Records generated by council
CREATE TABLE IF NOT EXISTS public.architecture_decisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  decision_number int UNIQUE NOT NULL,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'proposed',
  council_run_id uuid REFERENCES public.council_runs(id),
  context_md text NOT NULL,
  decision_md text NOT NULL,
  consequences_md text NOT NULL,
  superseded_by uuid REFERENCES public.architecture_decisions(id),
  proposed_at timestamptz NOT NULL DEFAULT now(),
  accepted_at timestamptz,
  accepted_by uuid REFERENCES auth.users(id)
);

ALTER TABLE public.architecture_decisions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read ADRs" ON public.architecture_decisions
  FOR SELECT USING (true);

CREATE POLICY "Team can insert ADRs" ON public.architecture_decisions
  FOR INSERT WITH CHECK (public.has_role(auth.uid(), 'team'));

CREATE POLICY "Team can update ADRs" ON public.architecture_decisions
  FOR UPDATE USING (public.has_role(auth.uid(), 'team'));

-- Monthly budget tracking
CREATE TABLE IF NOT EXISTS public.council_budget (
  month date PRIMARY KEY,
  spent_usd numeric NOT NULL DEFAULT 0,
  cap_usd numeric NOT NULL DEFAULT 50,
  alerts_sent jsonb DEFAULT '{"80":false,"100":false}'::jsonb,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.council_budget ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Team can read budget" ON public.council_budget
  FOR SELECT USING (public.has_role(auth.uid(), 'team'));
