// Phase 1.10am — Persistence + orchestration for the deep multi-turn wizard.
//
// Each session row in `wizard_sessions` (Supabase) carries the full WizardState
// from wizard-engine.ts. The HTTP layer (atlas/src/server.ts) calls into
// startSession / answerSession / getSession / deleteSession; this module is
// where Claude is invoked, state mutations are computed, and the row is
// upserted.
//
// Defensive on every Supabase call — if Supabase is unconfigured (dev mode
// without env vars), we keep an in-memory fallback so the cockpit still works
// for local testing.

import { getSupabaseClient } from './supabase'
import {
  applyDeepTurnResult,
  nextDeepTurn,
  recordWizardAnswer,
  MAX_WIZARD_TURNS,
  type WizardState,
  type DeepTurnResult,
} from './wizard-engine'

interface SessionRow {
  id: string
  phase_id: string
  state: WizardState
  created_at: string
  updated_at: string
  completed_at: string | null
  created_by: string | null
}

const memoryStore = new Map<string, SessionRow>()

function rowToPublic(row: SessionRow): WizardSessionPublic {
  return {
    id: row.id,
    phase_id: row.phase_id,
    state: row.state,
    created_at: row.created_at,
    updated_at: row.updated_at,
    completed_at: row.completed_at,
  }
}

export interface WizardSessionPublic {
  id: string
  phase_id: string
  state: WizardState
  created_at: string
  updated_at: string
  completed_at: string | null
}

export interface StartSessionInput {
  phaseId: string
  parentTitle: string
  parentBody: string
  phaseHint: string
  mode: 'add' | 'modify'
  existingSpec?: string
  conceptSummaries?: string[]
  createdBy?: string
}

export interface StartSessionResult {
  session: WizardSessionPublic
  source: 'claude' | 'fallback'
  costUsd: number
}

/**
 * Open a new wizard session and return the first turn. The first turn is
 * generated by Claude on creation so the UI has something to render
 * immediately.
 */
export async function startSession(input: StartSessionInput): Promise<StartSessionResult> {
  const initial: WizardState = {
    phase_id: input.phaseId,
    parent_title: input.parentTitle,
    parent_body: input.parentBody,
    phase_hint: input.phaseHint,
    mode: input.mode,
    existing_spec: input.existingSpec,
    concept_summaries: input.conceptSummaries,
    history: [],
    total_turns: 0,
    is_complete: false,
    clarity_score: 0,
  }
  const turn = await nextDeepTurn(initial)
  const stateAfter = applyDeepTurnResult(initial, turn.result)
  const row = await upsertSession(null, stateAfter, input.createdBy)
  return {
    session: rowToPublic(row),
    source: turn.source,
    costUsd: turn.costUsd,
  }
}

export interface AnswerSessionInput {
  sessionId: string
  answer: string
}

export interface AnswerSessionResult {
  session: WizardSessionPublic
  source: 'claude' | 'fallback'
  costUsd: number
  /** Final completion result if the wizard wrapped on this turn. */
  completion?: DeepTurnResult & { kind: 'complete' }
  reason?: string
}

/**
 * Record the user's answer to the current turn, then ask Claude for the next
 * turn. Wraps the wizard automatically if `total_turns` reaches the cap.
 */
export async function answerSession(input: AnswerSessionInput): Promise<AnswerSessionResult | { ok: false; reason: string }> {
  const row = await loadSession(input.sessionId)
  if (!row) return { ok: false, reason: 'session_not_found' }
  if (row.completed_at || row.state.is_complete) {
    return { ok: false, reason: 'session_already_complete' }
  }
  if (!row.state.current_turn) {
    return { ok: false, reason: 'no_current_turn' }
  }
  const trimmed = (input.answer ?? '').trim()
  if (!trimmed) return { ok: false, reason: 'answer_required' }

  const stateWithAnswer = recordWizardAnswer(row.state, trimmed)

  // 12-turn cap: force completion regardless of Claude's preference.
  let turn = await nextDeepTurn(stateWithAnswer)
  if (
    turn.result.kind === 'question' &&
    stateWithAnswer.total_turns >= MAX_WIZARD_TURNS
  ) {
    // Promote to completion with documented assumptions banner.
    const fallbackSpec = buildFallbackSpec(stateWithAnswer)
    turn = {
      result: {
        kind: 'complete',
        current_clarity: stateWithAnswer.clarity_score,
        summary_of_decisions: 'Wizard hit the 12-turn cap before reaching 100% clarity. The spec below documents every assumption I had to make.',
        spec_draft: fallbackSpec,
      },
      costUsd: turn.costUsd,
      source: 'fallback',
    }
  }
  const finalState = applyDeepTurnResult(stateWithAnswer, turn.result)
  const updated = await upsertSession(row.id, finalState, row.created_by, finalState.is_complete ? new Date().toISOString() : null)

  return {
    session: rowToPublic(updated),
    source: turn.source,
    costUsd: turn.costUsd,
    completion: turn.result.kind === 'complete' ? turn.result : undefined,
  }
}

export async function getSession(sessionId: string): Promise<WizardSessionPublic | null> {
  const row = await loadSession(sessionId)
  return row ? rowToPublic(row) : null
}

export async function deleteSession(sessionId: string): Promise<{ ok: boolean }> {
  const sb = getSupabaseClient()
  if (!sb) {
    memoryStore.delete(sessionId)
    return { ok: true }
  }
  const { error } = await sb.from('wizard_sessions').delete().eq('id', sessionId)
  if (error) {
    console.warn('[wizard-session] delete failed:', error.message)
    return { ok: false }
  }
  memoryStore.delete(sessionId)
  return { ok: true }
}

/**
 * Find the most recent in-progress session for a phase id (so the cockpit can
 * offer "Resume?" when the user reopens). Limited to the last 24 hours so
 * stale rows don't haunt the UI.
 */
export async function findResumableSession(phaseId: string): Promise<WizardSessionPublic | null> {
  const sb = getSupabaseClient()
  if (!sb) {
    const cutoff = Date.now() - 24 * 60 * 60 * 1000
    const candidates: SessionRow[] = []
    for (const row of memoryStore.values()) {
      if (row.phase_id !== phaseId) continue
      if (row.completed_at) continue
      if (Date.parse(row.updated_at) < cutoff) continue
      candidates.push(row)
    }
    candidates.sort((a, b) => b.updated_at.localeCompare(a.updated_at))
    return candidates[0] ? rowToPublic(candidates[0]) : null
  }
  const { data, error } = await sb
    .from('wizard_sessions')
    .select('*')
    .eq('phase_id', phaseId)
    .is('completed_at', null)
    .gte('updated_at', new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString())
    .order('updated_at', { ascending: false })
    .limit(1)
  if (error) {
    console.warn('[wizard-session] findResumable failed:', error.message)
    return null
  }
  const row = (data as SessionRow[] | null)?.[0]
  return row ? rowToPublic(row) : null
}

async function loadSession(sessionId: string): Promise<SessionRow | null> {
  const sb = getSupabaseClient()
  if (!sb) return memoryStore.get(sessionId) ?? null
  const { data, error } = await sb
    .from('wizard_sessions')
    .select('*')
    .eq('id', sessionId)
    .single()
  if (error || !data) {
    if (error && error.code !== 'PGRST116') {
      console.warn('[wizard-session] load failed:', error.message)
    }
    return memoryStore.get(sessionId) ?? null
  }
  return data as SessionRow
}

async function upsertSession(
  existingId: string | null,
  state: WizardState,
  createdBy?: string | null,
  completedAt: string | null = null,
): Promise<SessionRow> {
  const sb = getSupabaseClient()
  const now = new Date().toISOString()
  if (!sb) {
    const id = existingId ?? cryptoRandomId()
    const prior = existingId ? memoryStore.get(existingId) : null
    const row: SessionRow = {
      id,
      phase_id: state.phase_id,
      state,
      created_at: prior?.created_at ?? now,
      updated_at: now,
      completed_at: completedAt ?? prior?.completed_at ?? null,
      created_by: prior?.created_by ?? createdBy ?? null,
    }
    memoryStore.set(id, row)
    return row
  }
  if (existingId) {
    const update: Record<string, unknown> = { state, updated_at: now }
    if (completedAt) update.completed_at = completedAt
    const { data, error } = await sb
      .from('wizard_sessions')
      .update(update)
      .eq('id', existingId)
      .select('*')
      .single()
    if (error || !data) {
      throw new Error(`wizard_sessions update failed: ${error?.message ?? 'no row returned'}`)
    }
    return data as SessionRow
  }
  const insert: Record<string, unknown> = {
    phase_id: state.phase_id,
    state,
    created_by: createdBy ?? null,
  }
  if (completedAt) insert.completed_at = completedAt
  const { data, error } = await sb
    .from('wizard_sessions')
    .insert(insert)
    .select('*')
    .single()
  if (error || !data) {
    throw new Error(`wizard_sessions insert failed: ${error?.message ?? 'no row returned'}`)
  }
  return data as SessionRow
}

function cryptoRandomId(): string {
  // Lightweight UUIDv4 — Node's crypto.randomUUID is available on the Railway
  // runtime, but we keep a manual fallback in case the worker pool gives us a
  // stripped global. (No `crypto` import needed at module scope; inline.)
  const g = globalThis as { crypto?: { randomUUID?: () => string } }
  if (g.crypto?.randomUUID) return g.crypto.randomUUID()
  return 'ws-' + Math.random().toString(36).slice(2) + Date.now().toString(36)
}

/**
 * When the wizard hits the 12-turn cap without 100 clarity, we still need to
 * hand the user something Builder-shaped. This synthesizes a minimal spec
 * with a "Documented assumptions" section listing every Q/A pair so the
 * builder + reviewer have full context.
 */
function buildFallbackSpec(state: WizardState): string {
  const phase = state.phase_id || 'X.Y'
  const title = state.parent_title || 'wizard-generated phase'
  const qa = state.history
    .map((h, i) => `${i + 1}. **${h.question}** — ${h.answer}`)
    .join('\n')
  return `---
priority: 3
source: cockpit-wizard
phase: ${phase}
estimated_builder_minutes: 25
model: claude-opus-4-7
---

# Task: Phase ${phase} — ${title}

**Master plan reference:** §11 — phase added via deep cockpit wizard
**Estimated effort:** ~25 min Builder time
**Model:** claude-opus-4-7

model: claude-opus-4-7

---

## Goal

Ship the feature described by the deep-wizard interview below. The interview
hit its ${MAX_WIZARD_TURNS}-turn cap before reaching full clarity, so any
remaining gaps are listed under "Documented assumptions". Builder MUST
write a question file under \`.agent/questions/\` and stop if a documented
assumption turns out to be wrong.

## Documented assumptions

The wizard didn't reach 100% clarity before the turn cap. Builder operates
under the following assumptions unless flagged:

${qa || '- (no Q/A history captured)'}

## Architecture

(TBD — Builder selects exact files/components based on the assumptions above
and the linked repo facts gathered during the wizard.)

## Files

- (TBD by Builder)

## Success criteria

- \`npm run build\` clean.
- All wizard-answer behaviors observable in the UI.
- No assumption above turns out to break an information wall.

## Risks + mitigations

- **Risk:** Wizard didn't reach 100% clarity. **Mitigation:** Builder writes a question file the moment any documented assumption is violated.
- **Risk:** Information-wall breach. **Mitigation:** RLS at DB layer + role gate at component layer.

## NEVER list

- Never put AI provider keys in \`VITE_*\` env vars.
- Never break information walls.
- Never commit a broken build.
`
}

export const __test_only__ = {
  buildFallbackSpec,
  upsertSession,
  loadSession,
  memoryStore,
}
